name: pytest

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branch:
      main

jobs:
  ruff:
    name: pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Install dependencies
      run: |
        poetry config virtualenvs.create false
        poetry install --no-interaction --no-ansi
    - name: Run pytest
      run: |
        poetry shell
        poetry run pytest -v
